#!/system/bin/sh

mount -o rw,remount /system
if [ -f /data/property/persist.sys.mainkeys ];
then
   value=$(cat /data/property/persist.sys.mainkeys)
   if [ $value == "0" ];
   then
       cp -f /system/usr/keylayout/hwkeys_off.kl /system/usr/keylayout/mtk-tpd.kl 
   else
       cp -f /system/usr/keylayout/hwkeys_on.kl /system/usr/keylayout/mtk-tpd.kl 
   fi
else
       cp -f /system/usr/keylayout/hwkeys_on.kl /system/usr/keylayout/mtk-tpd.kl 
fi
mount -o ro,remount /system
